server:
  port: 8999

spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        tags:
          - urlprefix-/custom-analyzer strip=/custom-analyzer
          - analyzer=custom
          - analyzer_priority=0
          - analyzer_index=true
        register: true
      enabled: true
endpoints:
  info:
    enabled: true
    sensitive: false
  health:
    enabled: true
    sensitive: false
management:
  security:
    enabled: false
logging:
  level:
    root: debug
    sun.rmi: warn
    org.apache: warn
    org.springframework.core: warn
    org.springframework.beans: warn
    org.springframework.context: warn
    org.springframework.web: warn