server:
  port: 8999

spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        tags:
          - urlprefix-/custom-analyzer strip=/custom-analyzer
          - analyzer=custom
          - analyzer_priority=0
          - analyzer_index=true
        register: true
      enabled: true